// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Cleemy.Entities
{
    public partial class Expense
    {
        public int Id { get; set; }
        public DateTime ExpenseDate { get; set; }
        public decimal Amount { get; set; }
        public string Commentary { get; set; }
        public int FkCleemyUser { get; set; }
        public int FkExpenseNature { get; set; }

        public virtual CleemyUser FkCleemyUserNavigation { get; set; }
        public virtual ExpenseNature FkExpenseNatureNavigation { get; set; }
    }
}