// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Cleemy.Entities
{
    public partial class ExpenseNature
    {
        public ExpenseNature()
        {
            Expense = new HashSet<Expense>();
        }

        public int Id { get; set; }
        public string Name { get; set; }

        public virtual ICollection<Expense> Expense { get; set; }
    }
}